
var getUrlParam=function(name,url){var re=new RegExp('(?:^|[?&#])'+name+'=([^?&#]*)','i');var m=re.exec(url||window.location.href);return m?m[1]:'';};var ping=function(url){var img=document.createElement('img');img.onload=img.onerror=function(){img=null;};img.src=url;setTimeout(function(){},1000);};var hotClick=function(tag,domain,path){if(!tag){return;}
domain=domain||'sng.qq.com';path=path||window.location.pathname;var url=['http://pinghot.qq.com/pingd?dm=',domain,'.hot&url=',path,'&hottag=',tag,'&hotx=9999&hoty=9999&sds=',Math.random()].join('');ping(url);};var pv=function(sDomain,path,opts){var send=function(sDomain,path,opts){var _cookieP=/(?:^|;+|\s+)pgv_pvid=([^;]*)/i;var _cookieSSID=/(?:^|;+|\s+)pgv_info=([^;]*)/i;var _urlSpliter=/[\?\#]/;var pgv_pvid=(function(){var t,d,h,f;t=document.cookie.match(_cookieP);if(t&&t.length&&t.length>1){d=t[1];}else{d=(Math.round(Math.random()*2147483647)*(new Date().getUTCMilliseconds()))%10000000000;document.cookie="pgv_pvid="+d+"; path=/; domain=qq.com; expires=Sun, 18 Jan 2038 00:00:00 GMT;";}
h=document.cookie.match(_cookieSSID);if(!h){f=(Math.round(Math.random()*2147483647)*(new Date().getUTCMilliseconds()))%10000000000;document.cookie="pgv_info=ssid=s"+f+"; path=/; domain=qq.com;";}
return d;})();sDomain=sDomain||location.hostname||"-";path=path||location.pathname;opts=opts||{};opts.referURL=opts.referURL||document.referrer;var t,d,r;t=opts.referURL.split(_urlSpliter);t=t[0];t=t.split("/");d=t[2]||"-";r="/"+t.slice(3).join("/");opts.referDomain=opts.referDomain||d;opts.referPath=opts.referPath||r;var url='http://pingfore.qq.com/pingd?cc=-&ct=-&java=1&lang=-&pf=-&scl=-&scr=-&tt=-&tz=-8&vs=3.3&flash='
+'&dm='+sDomain
+'&url='+path
+'&rdm='+opts.referDomain
+'&rurl='+opts.referPath
+'&pgv_pvid='+pgv_pvid
+'&sds='+Math.random();ping(url);};opts=opts||{};var from=getUrlParam('from');if(from){path=path||location.pathname;var referPrefix=path.replace(/\..+/,'').split('/').slice(-2).join('-');opts.referDomain='ADTAG';opts.referPath=referPrefix+'.'+from;}
send(sDomain,path,opts);};if(typeof Zepto==='undefined'){throw new Error('Parallax.js\'s script requires Zepto')}!function($){var startPos,endPos,stage,offset,direction,curPage,pageCount,pageWidth,pageHeight,$pages,$pageArr,$animateDom,options,touchDown=false,movePrevent=true;$.fn.parallax=function(opts){options=$.extend({},$.fn.parallax.defaults,opts);return this.each(function(){$pages=$(this);$pageArr=$pages.find('.page');init();})}
$.fn.parallax.defaults={direction:'vertical',swipeAnim:'default',drag:true,loading:false,indicator:false,arrow:false,onchange:function(){},orientationchange:function(){}};function init(){if(options.loading){$('.wrapper').append('<div class="parallax-loading"><i class="ui-loading ui-loading-white"></i></div>');}else{movePrevent=false;}
curPage=0;direction='stay';pageCount=$pageArr.length;pageWidth=$(window).width();pageHeight=$(window).height();$animateDom=$('[data-animation]');for(var i=0;i<pageCount;i++){$($pageArr[i]).attr('data-id',i+1);}
$pages.addClass(options.direction).addClass(options.swipeAnim);$pageArr.css({'width':pageWidth+'px','height':pageHeight+'px'});options.direction==='horizontal'?$pages.css('width',pageWidth*$pageArr.length):$pages.css('height',pageHeight*$pageArr.length);if(options.swipeAnim==='cover'){$pages.css({'width':pageWidth,'height':pageHeight});$pageArr[0].style.display='block';}
if(!options.loading){$($pageArr[curPage]).addClass('current');options.onchange(curPage,$pageArr[curPage],direction);animShow();}}
function onStart(e){if(movePrevent===true){event.preventDefault();return false;}
touchDown=true;options.direction==='horizontal'?startPos=e.pageX:startPos=e.pageY;if(options.swipeAnim==='default'){$pages.addClass('drag');offset=$pages.css("-webkit-transform").replace("matrix(","").replace(")","").split(",");options.direction==='horizontal'?offset=parseInt(offset[4]):offset=parseInt(offset[5]);}
if((options.swipeAnim==='cover'&&options.drag)){$pageArr.addClass('drag');}
stage=1;}
function onMove(e){if(movePrevent===true||touchDown===false){event.preventDefault();return false;}
event.preventDefault();options.direction==='horizontal'?endPos=e.pageX:endPos=e.pageY;addDirecClass();if(options.drag&&!isHeadOrTail()){dragToMove();}
stage=2;}
function onEnd(e){if(movePrevent===true||stage!==2){}else{touchDown=false;options.direction==='horizontal'?endPos=e.pageX:endPos=e.pageY;if(options.swipeAnim==='default'&&!isHeadOrTail()){$pages.removeClass('drag');if(Math.abs(endPos-startPos)<=50){animatePage(curPage);direction='stay';}
else if(endPos>=startPos){animatePage(curPage-1);direction='backward';}
else if(endPos<startPos){animatePage(curPage+1);direction='forward';}}
else if(options.swipeAnim==='cover'&&!isHeadOrTail()){if(Math.abs(endPos-startPos)<=50&&endPos>=startPos&&options.drag){animatePage(curPage,'keep-backward');direction='stay';}
else if(Math.abs(endPos-startPos)<=50&&endPos<startPos&&options.drag){animatePage(curPage,'keep-forward');direction='stay';}
else if(Math.abs(endPos-startPos)>50&&endPos>=startPos&&options.drag){animatePage(curPage-1,'backward');direction='backward';}
else if(Math.abs(endPos-startPos)>50&&endPos<startPos&&options.drag){animatePage(curPage+1,'forward')
direction='forward';}
else if(Math.abs(endPos-startPos)>50&&endPos>=startPos&&!options.drag){animatePage(curPage-1,'backward');direction='backward';}
else if(Math.abs(endPos-startPos)>50&&endPos<startPos&&!options.drag){animatePage(curPage+1,'forward')
direction='forward';}}
if(options.indicator){$($('.parallax-h-indicator ul li, .parallax-v-indicator ul li').removeClass('current').get(curPage)).addClass('current');}
stage=3;}}
function dragToMove(){if(options.swipeAnim==='default'){var temp=offset+endPos-startPos;options.direction==='horizontal'?$pages.css("-webkit-transform","matrix(1, 0, 0, 1, "+temp+", 0)"):$pages.css("-webkit-transform","matrix(1, 0, 0, 1, 0, "+temp+")");}
else if(options.swipeAnim==='cover'){var temp=endPos-startPos,$prevPage=$($pageArr[curPage-1]),$nextPage=$($pageArr[curPage+1]);$($pageArr).css({'z-index':0});if(options.direction==='horizontal'&&endPos>=startPos){$prevPage.css({'z-index':2,'display':'block','-webkit-transform':'translateX('+(temp-pageWidth)+'px)'})}
else if(options.direction==='horizontal'&&endPos<startPos){$nextPage.css({'z-index':2,'display':'block','-webkit-transform':'translateX('+(pageWidth+temp)+'px)'})}
else if(options.direction==='vertical'&&endPos>=startPos){$prevPage.css({'z-index':2,'display':'block','-webkit-transform':'translateY('+(temp-pageHeight)+'px)'})}
else if(options.direction==='vertical'&&endPos<startPos){$nextPage.css({'z-index':2,'display':'block','-webkit-transform':'translateY('+(pageHeight+temp)+'px)'})}}}
function animatePage(newPage,action){curPage=newPage;if(options.swipeAnim==='default'){var newOffset=0;options.direction==='horizontal'?newOffset=newPage*(-pageWidth):newOffset=newPage*(-pageHeight);options.direction==='horizontal'?$pages.css({'-webkit-transform':'matrix(1, 0, 0, 1, '+newOffset+', 0)'}):$pages.css({'-webkit-transform':'matrix(1, 0, 0, 1, 0, '+newOffset+')'});}
else if(options.swipeAnim==='cover'){if(action==='keep-backward'&&options.drag){$pageArr.removeClass('drag');options.direction==='horizontal'?$($pageArr[curPage-1]).css({'-webkit-transform':'translateX(-100%)'}):$($pageArr[curPage-1]).css({'-webkit-transform':'translateY(-100%)'})}
else if(action==='keep-forward'&&options.drag){$pageArr.removeClass('drag');options.direction==='horizontal'?$($pageArr[curPage+1]).css({'-webkit-transform':'translateX(100%)'}):$($pageArr[curPage+1]).css({'-webkit-transform':'translateY(100%)'})}
else if(action==='forward'&&options.drag){$pageArr.removeClass('drag');$($pageArr[curPage-1]).addClass('back');$pageArr[curPage].style.webkitTransform='translate(0, 0)';}
else if(action==='backward'&&options.drag){$pageArr.removeClass('drag');$($pageArr[curPage+1]).addClass('back');$pageArr[curPage].style.webkitTransform='translate(0, 0)';}
else if(action==='forward'&&!options.drag){$pages.addClass('animate');$($pageArr[curPage-1]).addClass('back');$($pageArr[curPage]).addClass('front').show();}
else if(action==='backward'&&!options.drag){$pages.addClass('animate');$($pageArr[curPage+1]).addClass('back');$($pageArr[curPage]).addClass('front').show();}}
movePrevent=true;setTimeout(function(){movePrevent=false;},300);}
function addDirecClass(){if(options.direction==='horizontal'){if(endPos>=startPos){$pages.removeClass('forward').addClass('backward');}else if(endPos<startPos){$pages.removeClass('backward').addClass('forward');}}else{if(endPos>=startPos){$pages.removeClass('forward').addClass('backward');}else if(endPos<startPos){$pages.removeClass('backward').addClass('forward');}}}
function isHeadOrTail(){if(options.direction==='horizontal'){if((endPos>=startPos&&curPage===0)||(endPos<=startPos&&curPage===pageCount-1)){return true;}}else if((endPos>=startPos&&curPage===0)||(endPos<=startPos&&curPage===pageCount-1)){return true;}
return false;}
function animShow(){$animateDom.css({'-webkit-animation':'none','display':'none'});$('.current [data-animation]').each(function(index,element){var $element=$(element),$animation=$element.attr('data-animation'),$duration=$element.attr('data-duration')||500,$timfunc=$element.attr('data-timing-function')||'ease',$delay=$element.attr('data-delay')?$element.attr('data-delay'):0;if($animation==='followSlide'){if(options.direction==='horizontal'&&direction==='forward'){$animation='followSlideToLeft';}
else if(options.direction==='horizontal'&&direction==='backward'){$animation='followSlideToRight';}
else if(options.direction==='vertical'&&direction==='forward'){$animation='followSlideToTop';}
else if(options.direction==='vertical'&&direction==='backward'){$animation='followSlideToBottom';}}
$element.css({'display':'block','-webkit-animation-name':$animation,'-webkit-animation-duration':$duration+'ms','-webkit-animation-timing-function':'ease','-webkit-animation-timing-function':$timfunc,'-webkit-animation-delay':$delay+'ms','-webkit-animation-fill-mode':'both'})});}
$(document).on('touchstart','.page',function(e){onStart(e.changedTouches[0]);}).on('touchmove','.page',function(e){onMove(e.changedTouches[0]);}).on('touchend','.page',function(e){onEnd(e.changedTouches[0]);}).on('webkitAnimationEnd webkitTransitionEnd','.pages',function(){if(direction!=='stay'){setTimeout(function(){$(".back").hide().removeClass("back");$(".front").show().removeClass("front");$pages.removeClass('forward backward animate');},10);$($pageArr.removeClass('current').get(curPage)).addClass('current');options.onchange(curPage,$pageArr[curPage],direction);animShow();}});$('.page *').on('webkitAnimationEnd',function(){event.stopPropagation();})
$(window).on("load",function(){if(options.loading){$(".parallax-loading").remove();movePrevent=false;$($pageArr[curPage]).addClass('current');options.onchange(curPage,$pageArr[curPage],direction);animShow();}
if(options.indicator){movePrevent=false;var temp=options.direction==='horizontal'?'parallax-h-indicator':'parallax-v-indicator';$('.wrapper').append('<div class='+temp+'></div>');var lists='<ul>';for(var i=1;i<=pageCount;i++){if(i===1){lists+='<li class="current"></li>'}else{lists+='<li></li>'}}
lists+='</ul>';$('.'+temp).append(lists);}
if(options.arrow){$pageArr.append('<span class="parallax-arrow"></span>');$($pageArr[pageCount-1]).find('.parallax-arrow').remove();}});window.addEventListener("onorientationchange"in window?"orientationchange":"resize",function(){if(window.orientation===180||window.orientation===0){options.orientationchange('portrait');}
if(window.orientation===90||window.orientation===-90){options.orientationchange('landscape')}},false);}(Zepto);(function(){function loadImg(obj,src,callBack,error){obj.onload=function(){typeof callBack=="function"&&callBack();};obj.onerror=function(){typeof error==="function"&&error()};obj.src=src;};function load(loadImgSrcArr,callBack){var loadI=0;var totalImg=loadImgSrcArr.length;for(var i=0;i<totalImg;i++){var image=new Image();loadImg(image,loadImgSrcArr[i],function(){loadI++;if(loadI==totalImg){setTimeout(function(){typeof callBack=="function"&&callBack();},300);};});};};var loadImgSrcArr=['img/loading.png','img/page1_2.png','img/page1Bg.png'];load(loadImgSrcArr,function(){$('.loadingWrap').hide();$('.page1_text1').css('-webkit-animation','followSlideToTop 1000ms ease 0ms both; display: block;')
$('.page1_text2').css('-webkit-animation','followSlideToTop 1200ms ease 1000ms both; display: block;')
var audio=document.getElementById('audio');audio.volume=0.3;$("body").one("touchstart",function(){audio.play();$('.musciBtn').removeClass('musicOff');});});$('.pages').parallax({direction:'vertical',swipeAnim:'cover',drag:true,loading:false,indicator:false,arrow:true,onchange:function(index,element,direction){},orientationchange:function(orientation){}});$('.page11_text4').on('tap click',function(){$('.mark').show();$('.musciBtn').hide();});$('.mark').on('touchstart',function(){$('.mark').hide();$('.musciBtn').show();});$('.musciBtn').on('tap click',function(){console.log('trigger');$(this).toggleClass('musicOff');var audio=document.getElementById('audio');if(audio!==null){if(!audio.paused){audio.pause();}else{audio.play();}}})
var shareInfo={title:'QQ物联智能硬件免费领即将开启',desc:'这一年……，总得带点什么回去吧？温暖新年，领礼回家！',link:'http://iot.qq.com/iotactivityshow',imgUrl:'http://i.gtimg.cn/qzonestyle/act/qzone_publicize_img/iotlogo.png'};if(isWechat){document.addEventListener('WeixinJSBridgeReady',function(){wx.onMenuShareTimeline(shareInfo);wx.onMenuShareAppMessage(shareInfo);wx.onMenuShareQQ(shareInfo);wx.onMenuShareWeibo(shareInfo);},false);}else if(isQQ){mqq.data.setShareInfo({title:shareInfo.title,desc:shareInfo.desc,share_url:shareInfo.link,image_url:shareInfo.imgUrl});}
pv('open.qq.com','/iotactivityshow');})();/*  |xGv00|9248e1ef368c0e7d898d7aaa08b2e1cf */